#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace airbornefrs.Data.DBML
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="shieliteexpress")]
	public partial class airbornefrsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public airbornefrsDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["shieliteexpressConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public airbornefrsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public airbornefrsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public airbornefrsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public airbornefrsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.emailSettings_GET_sp_V02")]
		public ISingleResult<emailSettings_GET_sp_V02Result> emailSettings_GET_sp_V02([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> emailsettingid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), emailsettingid);
			return ((ISingleResult<emailSettings_GET_sp_V02Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Support_ContactUs_General_Save_SP")]
		public ISingleResult<Support_ContactUs_General_Save_SPResult> Support_ContactUs_General_Save_SP([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="VarChar(100)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(100)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CompanyName", DbType="VarChar(100)")] string companyName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReasonInquiry", DbType="VarChar(20)")] string reasonInquiry, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Product", DbType="VarChar(100)")] string product, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IMEI", DbType="VarChar(130)")] string iMEI, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdditionalInfo", DbType="VarChar(500)")] string additionalInfo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, email, companyName, reasonInquiry, product, iMEI, additionalInfo);
			return ((ISingleResult<Support_ContactUs_General_Save_SPResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Support_SupportTicket_PurchasedProduct_Save_SP")]
		public ISingleResult<Support_SupportTicket_PurchasedProduct_Save_SPResult> Support_SupportTicket_PurchasedProduct_Save_SP([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="VarChar(100)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(100)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CompanyName", DbType="VarChar(100)")] string companyName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Product", DbType="VarChar(100)")] string product, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IMEI", DbType="VarChar(130)")] string iMEI, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Location", DbType="VarChar(20)")] string location, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Howcanwehelp", DbType="NVarChar(500)")] string howcanwehelp)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, email, companyName, product, iMEI, location, howcanwehelp);
			return ((ISingleResult<Support_SupportTicket_PurchasedProduct_Save_SPResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Support_RMA_Save_SP")]
		public ISingleResult<Support_RMA_Save_SPResult> Support_RMA_Save_SP([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="VarChar(100)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(100)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Zipcode", DbType="NVarChar(10)")] string zipcode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Country", DbType="VarChar(50)")] string country, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IMEI", DbType="VarChar(130)")] string iMEI, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DID", DbType="VarChar(50)")] string dID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Product", DbType="VarChar(100)")] string product, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Waspersonalorbuz", DbType="VarChar(20)")] string waspersonalorbuz)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, email, zipcode, country, iMEI, dID, product, waspersonalorbuz);
			return ((ISingleResult<Support_RMA_Save_SPResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Support_ContactUs_Reseller_Save_SP")]
		public ISingleResult<Support_ContactUs_Reseller_Save_SPResult> Support_ContactUs_Reseller_Save_SP([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="VarChar(100)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(100)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CompanyName", DbType="VarChar(100)")] string companyName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telephone", DbType="NVarChar(20)")] string telephone, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TeleType", DbType="VarChar(20)")] string teleType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BuisnessType", DbType="VarChar(100)")] string buisnessType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdditionalInfo", DbType="NVarChar(500)")] string additionalInfo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, email, companyName, telephone, teleType, buisnessType, additionalInfo);
			return ((ISingleResult<Support_ContactUs_Reseller_Save_SPResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Support_ContactUs_CorporateAdvertising_Save_SP")]
		public ISingleResult<Support_ContactUs_CorporateAdvertising_Save_SPResult> Support_ContactUs_CorporateAdvertising_Save_SP([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="VarChar(100)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(100)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CompanyName", DbType="VarChar(100)")] string companyName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telephone", DbType="NVarChar(20)")] string telephone, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TeleType", DbType="VarChar(20)")] string teleType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BuisnessType", DbType="VarChar(100)")] string buisnessType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Location", DbType="VarChar(20)")] string location, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdditionalInfo", DbType="NVarChar(500)")] string additionalInfo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, email, companyName, telephone, teleType, buisnessType, location, additionalInfo);
			return ((ISingleResult<Support_ContactUs_CorporateAdvertising_Save_SPResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Support_SupportTicket_PreSales_Save_SP")]
		public ISingleResult<Support_SupportTicket_PreSales_Save_SPResult> Support_SupportTicket_PreSales_Save_SP([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="VarChar(100)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(100)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CompanyName", DbType="VarChar(100)")] string companyName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BuisnessType", DbType="VarChar(100)")] string buisnessType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OtherProductIntrest", DbType="VarChar(100)")] string otherProductIntrest, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Use", DbType="VarChar(20)")] string use, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Location", DbType="VarChar(20)")] string location, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdditionalInfo", DbType="NVarChar(500)")] string additionalInfo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, email, companyName, buisnessType, otherProductIntrest, use, location, additionalInfo);
			return ((ISingleResult<Support_SupportTicket_PreSales_Save_SPResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Support_SupportTicket_MobileApp_Save_SP")]
		public ISingleResult<Support_SupportTicket_MobileApp_Save_SPResult> Support_SupportTicket_MobileApp_Save_SP([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="VarChar(100)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(100)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CompanyName", DbType="VarChar(100)")] string companyName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OperatingSys", DbType="VarChar(20)")] string operatingSys, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PrimaryPlat", DbType="VarChar(20)")] string primaryPlat, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Phone", DbType="VarChar(50)")] string phone, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Use", DbType="VarChar(20)")] string use, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Howcanwehelp", DbType="NVarChar(500)")] string howcanwehelp)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, email, companyName, operatingSys, primaryPlat, phone, use, howcanwehelp);
			return ((ISingleResult<Support_SupportTicket_MobileApp_Save_SPResult>)(result.ReturnValue));
		}
	}
	
	public partial class emailSettings_GET_sp_V02Result
	{
		
		private int _emailsettingid;
		
		private string _outgoingsmtp;
		
		private string _port;
		
		private string _fromemailaddress;
		
		private string _emailpwd;
		
		private string _fromemailname;
		
		private byte _enablessl;
		
		private string _defaultto;
		
		private string _defaultcc;
		
		private string _defaultbcc;
		
		private string _subject;
		
		private byte _isbodyhtml;
		
		private string _defaultmailbody;
		
		private System.Nullable<int> _OrgId;
		
		public emailSettings_GET_sp_V02Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailsettingid", DbType="Int NOT NULL")]
		public int emailsettingid
		{
			get
			{
				return this._emailsettingid;
			}
			set
			{
				if ((this._emailsettingid != value))
				{
					this._emailsettingid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outgoingsmtp", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string outgoingsmtp
		{
			get
			{
				return this._outgoingsmtp;
			}
			set
			{
				if ((this._outgoingsmtp != value))
				{
					this._outgoingsmtp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_port", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string port
		{
			get
			{
				return this._port;
			}
			set
			{
				if ((this._port != value))
				{
					this._port = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fromemailaddress", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string fromemailaddress
		{
			get
			{
				return this._fromemailaddress;
			}
			set
			{
				if ((this._fromemailaddress != value))
				{
					this._fromemailaddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailpwd", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string emailpwd
		{
			get
			{
				return this._emailpwd;
			}
			set
			{
				if ((this._emailpwd != value))
				{
					this._emailpwd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fromemailname", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string fromemailname
		{
			get
			{
				return this._fromemailname;
			}
			set
			{
				if ((this._fromemailname != value))
				{
					this._fromemailname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enablessl", DbType="TinyInt NOT NULL")]
		public byte enablessl
		{
			get
			{
				return this._enablessl;
			}
			set
			{
				if ((this._enablessl != value))
				{
					this._enablessl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_defaultto", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string defaultto
		{
			get
			{
				return this._defaultto;
			}
			set
			{
				if ((this._defaultto != value))
				{
					this._defaultto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_defaultcc", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string defaultcc
		{
			get
			{
				return this._defaultcc;
			}
			set
			{
				if ((this._defaultcc != value))
				{
					this._defaultcc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_defaultbcc", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string defaultbcc
		{
			get
			{
				return this._defaultbcc;
			}
			set
			{
				if ((this._defaultbcc != value))
				{
					this._defaultbcc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subject", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string subject
		{
			get
			{
				return this._subject;
			}
			set
			{
				if ((this._subject != value))
				{
					this._subject = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isbodyhtml", DbType="TinyInt NOT NULL")]
		public byte isbodyhtml
		{
			get
			{
				return this._isbodyhtml;
			}
			set
			{
				if ((this._isbodyhtml != value))
				{
					this._isbodyhtml = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_defaultmailbody", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string defaultmailbody
		{
			get
			{
				return this._defaultmailbody;
			}
			set
			{
				if ((this._defaultmailbody != value))
				{
					this._defaultmailbody = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrgId", DbType="Int")]
		public System.Nullable<int> OrgId
		{
			get
			{
				return this._OrgId;
			}
			set
			{
				if ((this._OrgId != value))
				{
					this._OrgId = value;
				}
			}
		}
	}
	
	public partial class Support_ContactUs_General_Save_SPResult
	{
		
		private System.Nullable<System.Guid> _ID;
		
		private System.Nullable<int> _ErrorCode;
		
		public Support_ContactUs_General_Save_SPResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorCode", DbType="Int")]
		public System.Nullable<int> ErrorCode
		{
			get
			{
				return this._ErrorCode;
			}
			set
			{
				if ((this._ErrorCode != value))
				{
					this._ErrorCode = value;
				}
			}
		}
	}
	
	public partial class Support_SupportTicket_PurchasedProduct_Save_SPResult
	{
		
		private System.Nullable<System.Guid> _ID;
		
		private System.Nullable<int> _ErrorCode;
		
		public Support_SupportTicket_PurchasedProduct_Save_SPResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorCode", DbType="Int")]
		public System.Nullable<int> ErrorCode
		{
			get
			{
				return this._ErrorCode;
			}
			set
			{
				if ((this._ErrorCode != value))
				{
					this._ErrorCode = value;
				}
			}
		}
	}
	
	public partial class Support_RMA_Save_SPResult
	{
		
		private System.Nullable<System.Guid> _ID;
		
		private System.Nullable<int> _ErrorCode;
		
		public Support_RMA_Save_SPResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorCode", DbType="Int")]
		public System.Nullable<int> ErrorCode
		{
			get
			{
				return this._ErrorCode;
			}
			set
			{
				if ((this._ErrorCode != value))
				{
					this._ErrorCode = value;
				}
			}
		}
	}
	
	public partial class Support_ContactUs_Reseller_Save_SPResult
	{
		
		private System.Nullable<System.Guid> _ID;
		
		private System.Nullable<int> _ErrorCode;
		
		public Support_ContactUs_Reseller_Save_SPResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorCode", DbType="Int")]
		public System.Nullable<int> ErrorCode
		{
			get
			{
				return this._ErrorCode;
			}
			set
			{
				if ((this._ErrorCode != value))
				{
					this._ErrorCode = value;
				}
			}
		}
	}
	
	public partial class Support_ContactUs_CorporateAdvertising_Save_SPResult
	{
		
		private System.Nullable<System.Guid> _ID;
		
		private System.Nullable<int> _ErrorCode;
		
		public Support_ContactUs_CorporateAdvertising_Save_SPResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorCode", DbType="Int")]
		public System.Nullable<int> ErrorCode
		{
			get
			{
				return this._ErrorCode;
			}
			set
			{
				if ((this._ErrorCode != value))
				{
					this._ErrorCode = value;
				}
			}
		}
	}
	
	public partial class Support_SupportTicket_PreSales_Save_SPResult
	{
		
		private System.Nullable<System.Guid> _ID;
		
		private System.Nullable<int> _ErrorCode;
		
		public Support_SupportTicket_PreSales_Save_SPResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorCode", DbType="Int")]
		public System.Nullable<int> ErrorCode
		{
			get
			{
				return this._ErrorCode;
			}
			set
			{
				if ((this._ErrorCode != value))
				{
					this._ErrorCode = value;
				}
			}
		}
	}
	
	public partial class Support_SupportTicket_MobileApp_Save_SPResult
	{
		
		private System.Nullable<System.Guid> _ID;
		
		private System.Nullable<int> _ErrorCode;
		
		public Support_SupportTicket_MobileApp_Save_SPResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorCode", DbType="Int")]
		public System.Nullable<int> ErrorCode
		{
			get
			{
				return this._ErrorCode;
			}
			set
			{
				if ((this._ErrorCode != value))
				{
					this._ErrorCode = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
