//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace airbornefrs.Data.EcommerceEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_AirborneEntities : DbContext
    {
        public db_AirborneEntities()
            : base("name=db_AirborneEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<airport_frequencies> airport_frequencies { get; set; }
        public virtual DbSet<airport> airports { get; set; }
        public virtual DbSet<country> countries { get; set; }
        public virtual DbSet<ItemDetail> ItemDetails { get; set; }
        public virtual DbSet<navaid> navaids { get; set; }
        public virtual DbSet<Order_Items> Order_Items { get; set; }
        public virtual DbSet<Order_Payments> Order_Payments { get; set; }
        public virtual DbSet<region> regions { get; set; }
        public virtual DbSet<runway> runways { get; set; }
    }
}
