//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace airbornefrs.Data.EcommerceEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class navaid
    {
        public long id { get; set; }
        public string filename { get; set; }
        public string ident { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public string frequency_khz { get; set; }
        public string latitude_deg { get; set; }
        public string longitude_deg { get; set; }
        public string elevation_ft { get; set; }
        public string iso_country { get; set; }
        public string dme_frequency_khz { get; set; }
        public string dme_channel { get; set; }
        public string dme_latitude_deg { get; set; }
        public string dme_longitude_deg { get; set; }
        public string dme_elevation_ft { get; set; }
        public string slaved_variation_deg { get; set; }
        public string magnetic_variation_deg { get; set; }
        public string usageType { get; set; }
        public string power { get; set; }
        public string associated_airport { get; set; }
    }
}
