//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace airbornefrs.Data.EcommerceEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Items
    {
        public long ID { get; set; }
        public string OrderID { get; set; }
        public Nullable<long> ProductID { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<decimal> ShippingPerUnit { get; set; }
        public Nullable<decimal> TaxPerUnit { get; set; }
    
        public virtual Order_Payments Order_Payments { get; set; }
    }
}
