//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace airbornefrs.Data.EcommerceEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Payments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order_Payments()
        {
            this.Order_Items = new HashSet<Order_Items>();
        }
    
        public long ID { get; set; }
        public string PaypalTransactionID { get; set; }
        public string OrderID { get; set; }
        public string OrderDescription { get; set; }
        public Nullable<decimal> OrderPrice { get; set; }
        public Nullable<int> OrderItems { get; set; }
        public string Email { get; set; }
        public string ShippingAddress { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<decimal> ShippingPrice { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public string RecipientName { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string CountryCode { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<bool> PhoneType { get; set; }
        public Nullable<bool> AcceptMessage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Items> Order_Items { get; set; }
    }
}
